
export default function Release(){ 
  return (
    <div className="min-h-screen bg-gradient-to-br from-pink-50 to-yellow-50 p-6">
      <h1 className="text-4xl font-bold mb-6 text-center">⚠️ Release of Liability</h1>
      <p className="leading-relaxed"><span class='text-3xl'>Attendance is voluntary and undertaken with full knowledge that caramel stations, a chocolate fountain, and craft zones introduce sticky surfaces, potential spills, </span><span class='text-2xl'>and high energy. Guardians agree to supervise their own minors continuously and accept responsibility for choices about food, play, crafts, and outdoor </span><span class='text-xl'>exploration. Participants waive and release all claims against hosts, volunteers, organizers, and property owners for ordinary negligence and for conditions inherent to </span><span class='text-lg'>joyful, chaotic events. Risks include slips on grass or pavement, minor collisions, paint smudges, glitter transfer, sprinkle scatter, chocolate‑related wardrobe surprises, and </span><span class='text-base'>momentary sugar‑fueled zigzags. Children may climb trees, balance on low structures, experiment with toy zip lines, or invent new games; if a </span><span class='text-sm'>child falls or is otherwise injured, responsibility rests with the parent or guardian. Hosts are not responsible for lost, stolen, damaged, or </span><span class='text-xs'>sticky items including clothing, shoes, bags, electronics, toys, or strollers. Food is buffet‑style and self‑served; allergens may be present; guests manage their </span><span class='text-[10px]'>own dietary choices and monitor children accordingly. Basic first aid may be offered; any additional medical care is sought and paid for </span><span class='text-[8px]'>by the participant or guardian. By remaining at Caramel Apple / Pumpkin Art / Chaos you consent to friendly photos for personal </span><span class='text-[6px]'>sharing among attendees unless you opt out to the organizer. Please behave considerately toward neighbors and other guests, keep walkways clear, dispose </span><span class='text-[5px]'>of sticks and wrappers promptly, and keep hair and clothing away from the fountain. Surfaces can be uneven; weather can introduce moisture; </span><span class='text-[4px]'>craft supplies may leave color on skin or fabric despite care; you assume these risks. Shared equipment is casual grade; inspect items </span><span class='text-[3px]'>before use and discontinue anything that seems unsuitable for your child. To the fullest extent permitted by law, claims are released and </span><span class='text-[2px]'>liabilities disclaimed; nothing here limits non‑waivable rights. If any term is found unenforceable, remaining terms continue in effect to the maximum extent </span><span class='text-[1px]'>allowed. Venue rules and organizer instructions should be followed for the comfort and safety of everyone. Participation signals understanding that minor bumps, </span><span class='text-[1px]'>final micro‑print: intentionally unreadable.</span></p>
    </div>
  )
}
